wants:
  - metadata:
      name: coffee-break
      type: reminder
    spec:
      params:
        message: "Time for a coffee break! â˜•"
        duration_from_now: "15 minutes"
        require_reaction: true
