wants:
  - metadata:
      name: my-reminder
      type: reminder
      labels:
        role: reaction_provider
    spec:
      params:
        message: "Connect to silencer test"
        duration_from_now: "10 seconds"
        ahead: "5 seconds"
        require_reaction: true

  - metadata:
      name: my-silencer
      type: silencer
    spec:
      params:
        policy: all_true
      using:
        - role: reaction_provider
