wants:
  - metadata:
      name: dynamic travel planner
      type: dynamic travel change
      labels:
        role: dynamic-travel-planner
    spec:
      params:
        prefix: dynamic-travel
        display_name: "Dynamic Travel Itinerary with Flight API"
        server_url: "http://localhost:8090"
        flight_number: "AA100"
        flight_type: "business class"
        from: "New York"
        to: "Los Angeles"
        departure_date: "2026-12-20"
        flight_duration: 12.0
        restaurant_type: "fine dining"
        hotel_type: "luxury"
        buffet_type: "international"
        dinner_duration: 2.0
